import { useState } from "react";
import { NavLink, Outlet, Route, Routes } from "react-router-dom";

const Icon=({children})=><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{children}</svg>;
const Spark=()=> <Icon><path d="m12 2 1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2Z"/></Icon>;
const icons={chat:<Icon><path d="M20 15a4 4 0 0 1-4 4H8l-4 3V7a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4Z"/><path d="M8 10h8M8 14h5"/></Icon>,memory:<Icon><path d="M12 5a3 3 0 0 0-5.5 1.7A3.5 3.5 0 0 0 7 13.5V16a3 3 0 0 0 5 2.2A3 3 0 0 0 17 16v-2.5a3.5 3.5 0 0 0 .5-6.8A3 3 0 0 0 12 5Z"/><path d="M12 5v14M8 10h4M12 10h4"/></Icon>,analytics:<Icon><path d="M4 19V5M4 19h17"/><path d="m7 15 4-4 3 2 5-6"/></Icon>};
function Layout(){const[open,setOpen]=useState(false);const links=[["/","chat","Chat"],["/memory","memory","Memory"],["/analytics","analytics","Analytics"]];return <div className="shell"><button className="scrim" onClick={()=>setOpen(false)}/><aside className={open?"open":""}><div className="brand"><span><Spark/></span>memento <button onClick={()=>setOpen(false)}>×</button></div><button className="new">＋ New conversation <i>⌘ K</i></button><nav>{links.map(([to,icon,text])=><NavLink end={to==="/"} to={to} key={text} onClick={()=>setOpen(false)}>{icons[icon]}{text}{text==="Memory"&&<b>6</b>}</NavLink>)}</nav><div className="profile"><div>M</div><p><strong>Maya's Creator Hub</strong><small>College lifestyle</small></p><em>•••</em></div></aside><button className="menu" onClick={()=>setOpen(true)}>☰</button><Outlet/></div>}
const messages=[["ai","Hey Maya — I’m your social memory agent. I remember your audience loves short, relatable campus content. What are we planning today?"],["you","What should I post tomorrow?"],["ai","Try a 12–15 second “things only college students understand” reel. Your recent reels have been strongest, and your audience tends to engage most around 7:30 PM. Keep the hook playful and get to the punchline in the first two seconds."]];
function Chat(){const[list,setList]=useState(messages),[text,setText]=useState(""),[typing,setTyping]=useState(false);function send(e){e.preventDefault();if(!text.trim())return;setList(x=>[...x,["you",text]]);setText("");setTyping(true);setTimeout(()=>{setList(x=>[...x,["ai","That’s a strong direction. For your college audience, make it specific, quick, and easy to share — a short relatable reel around 7:30 PM will give you the best chance of engagement."]]);setTyping(false)},750)}return <main className="chat page"><header><div><label>YOUR SOCIAL MEMORY AGENT</label><h1>Good evening, Maya <span>✦</span></h1></div><p className="status">● Memory active</p></header><section className="remember"><span>{icons.memory}</span><p><b>I remember:</b> Your college audience loves relatable reels, casual humor, and evening posts.</p><a>View memory →</a></section><div className="conversation">{list.map(([role,body],i)=><article className={role} key={i}>{role==="ai"&&<span className="bot"><Spark/></span>}<div><label>{role==="ai"?"MEMENTO":"YOU"}</label><p>{body}</p></div></article>)}{typing&&<article className="ai"><span className="bot"><Spark/></span><div><label>MEMENTO</label><p className="dots">•••</p></div></article>}</div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about your next post..."/><button>➤</button></form><small className="note">Memento uses your saved context to make every suggestion personal.</small></main>}
const cards=[["👥","Audience","College students","18–24 · campus lifestyle"],["✦","Preferred tone","Playful & relatable","Casual, meme-aware humor"],["◷","Best posting time","7:30 PM","Weekdays · local time"],["◉","Top format","Short-form reels","2.4× more engagement"]];
function Memory(){const timeline=[["Audience learned","College students respond to campus-specific humor","Today"],["Best format confirmed","Reels are outperforming carousels by 2.4×","Yesterday"],["Posting time refined","Weekday evenings have the highest saves","Sep 24"],["Tone captured","Keep the voice playful, direct, and a little chaotic","Sep 21"]];return <main className="page dashboard"><header><div><label>YOUR LONG-TERM CONTEXT</label><h1>Memory dashboard <span>✦</span></h1><p>The things Memento remembers to make your content feel personal.</p></div><p className="status">◉ <b>6</b> active memories</p></header><section className="cards">{cards.map(c=><div className="card" key={c[1]}><i>{c[0]}</i><label>{c[1]}</label><h3>{c[2]}</h3><p>{c[3]}</p></div>)}</section><section className="panel"><div className="title"><div><label>MEMORY TIMELINE</label><h2>Recent learnings</h2></div><small>● Always learning</small></div>{timeline.map((x,i)=><div className="timeline" key={x[0]}><i>{i===0?"✦":"•"}</i><div><h4>{x[0]}</h4><p>{x[1]}</p></div><time>{x[2]}</time></div>)}</section></main>}
const seed=[["Reel",520,60,90,"Sep 26"],["Carousel",285,31,22,"Sep 23"],["Reel",490,54,81,"Sep 19"],["Static post",210,18,12,"Sep 16"],["Reel",440,48,72,"Sep 12"]];
function Analytics(){const[rows,setRows]=useState(seed),[form,setForm]=useState({type:"Reel",likes:"",comments:"",shares:""});function save(e){e.preventDefault();setRows(x=>[[form.type,+form.likes,+form.comments,+form.shares,"Just now"],...x]);setForm({type:"Reel",likes:"",comments:"",shares:""})}return <main className="page dashboard"><header><div><label>MANUAL PERFORMANCE LOG</label><h1>Content analytics <span>✦</span></h1><p>Log your results. Memento turns them into better next-post recommendations.</p></div></header><div className="split"><section className="panel log"><div className="title"><div><label>NEW ENTRY</label><h2>Log a post</h2></div><i>✦</i></div><form onSubmit={save}><label>Post type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Reel</option><option>Carousel</option><option>Static post</option><option>Story</option></select></label><div className="fields">{["likes","comments","shares"].map(k=><label key={k}>{k}<input required min="0" type="number" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k==="likes"?"e.g. 520":k==="comments"?"e.g. 60":"e.g. 90"}/></label>)}</div><button className="save">Save performance →</button></form></section><section className="insight"><label>CURRENT INSIGHT</label><i>↗</i><h2>Reels are your momentum format.</h2><p>Your top three engagement days included a short-form reel. Keep the pacing punchy and post in the evening.</p><div><b>2.4×</b><span>more engagement<br/>than carousels</span></div></section></div><section className="panel table"><div className="title"><div><label>HISTORY</label><h2>Previous entries</h2></div><small>{rows.length} logged posts</small></div><table><thead><tr><th>Post</th><th>Likes</th><th>Comments</th><th>Shares</th><th>Total engagement</th><th>Logged</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><mark className={r[0]==="Reel"?"reel":""}>{r[0]}</mark></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><b>{r[1]+r[2]+r[3]}</b></td><td>{r[4]}</td></tr>)}</tbody></table></section></main>}
export default function App(){return <Routes><Route element={<Layout/>}><Route index element={<Chat/>}/><Route path="memory" element={<Memory/>}/><Route path="analytics" element={<Analytics/>}/></Route></Routes>}
